from __future__ import annotations

from dataclasses import dataclass
from typing import Callable, Protocol


@dataclass(slots=True)
class BridgeSignal:
    state: str
    seq: int = -1
    detail: dict | None = None
    fault_code: str = ''


class StationAdapter(Protocol):
    def set_callback(self, callback: Callable[[BridgeSignal], None]) -> None: ...
    def send_feed(self, seq: int, payload: bytes) -> None: ...
    def send_sort(self, seq: int, payload: bytes) -> None: ...
    def send_heartbeat(self, seq: int) -> None: ...
    def reset_fault(self, seq: int, payload: bytes = b'') -> None: ...
    def query_capabilities(self, seq: int) -> None: ...
    def poll(self) -> None: ...
    def close(self) -> None: ...
