#pragma once

// Generated by upper_computer/scripts/sync_action_registry.py.
#include <cstddef>
#include <cstdint>
#include "inspection_station_config.h"
#include "../lib/inspection_station_contract/generated/inspection_station_action_codes_generated.hpp"

struct InspectionStationActionRoute {
    std::uint8_t action_code;
    GPIO_TypeDef* gpio;
    uint16_t pin;
};

constexpr InspectionStationActionRoute INSPECTION_STATION_ACTION_ROUTES[] = {
    {INSPECTION_ACTION_CODE_SORT_OK, INSPECTION_SORT_OK_GPIO, INSPECTION_SORT_OK_PIN},
    {INSPECTION_ACTION_CODE_SORT_NG, INSPECTION_SORT_NG_GPIO, INSPECTION_SORT_NG_PIN},
    {INSPECTION_ACTION_CODE_SORT_RECHECK, INSPECTION_SORT_RECHECK_GPIO, INSPECTION_SORT_RECHECK_PIN},
};

constexpr std::size_t INSPECTION_STATION_ACTION_ROUTE_COUNT =
    sizeof(INSPECTION_STATION_ACTION_ROUTES) / sizeof(INSPECTION_STATION_ACTION_ROUTES[0]);
