[platformio]
default_envs = bluepill_f103c8

[env:bluepill_f103c8]
platform = ststm32
board = bluepill_f103c8
framework = stm32cube
monitor_speed = 115200
upload_protocol = stlink
build_flags =
    -DINSPECTION_FW_VERSION=\"stm32-station-pio-v1\"
    -DINSPECTION_DEVICE_ID=\"stm32-station-01\"
    -DINSPECTION_PROTOCOL_VERSION=\"v1\"
    -DINSPECTION_FEED_PULSE_MS=80
    -DINSPECTION_SORT_PULSE_MS=120
    -DINSPECTION_POSITION_DELAY_MS=300
    -DINSPECTION_SORT_DONE_DELAY_MS=400
    -DINSPECTION_HEARTBEAT_INTERVAL_MS=1000
