#pragma once

#include <stdint.h>
#include "stm32f1xx_hal.h"

#ifndef INSPECTION_FW_VERSION
#define INSPECTION_FW_VERSION "stm32-station-pio-v1"
#endif

#ifndef INSPECTION_DEVICE_ID
#define INSPECTION_DEVICE_ID "stm32-station-01"
#endif

#ifndef INSPECTION_PROTOCOL_VERSION
#define INSPECTION_PROTOCOL_VERSION "1.0"
#endif

#ifndef INSPECTION_FEED_PULSE_MS
#define INSPECTION_FEED_PULSE_MS 80U
#endif

#ifndef INSPECTION_SORT_PULSE_MS
#define INSPECTION_SORT_PULSE_MS 120U
#endif

#ifndef INSPECTION_POSITION_DELAY_MS
#define INSPECTION_POSITION_DELAY_MS 300U
#endif

#ifndef INSPECTION_SORT_DONE_DELAY_MS
#define INSPECTION_SORT_DONE_DELAY_MS 400U
#endif

#ifndef INSPECTION_HEARTBEAT_INTERVAL_MS
#define INSPECTION_HEARTBEAT_INTERVAL_MS 1000U
#endif

// USART1 TX/RX on PA9 / PA10 for BluePill.
#define INSPECTION_UART_INSTANCE USART1

// Example GPIO mapping; adjust to the real wiring before deployment.
#define INSPECTION_LED_GPIO GPIOC
#define INSPECTION_LED_PIN GPIO_PIN_13

#define INSPECTION_FEED_GPIO GPIOB
#define INSPECTION_FEED_PIN GPIO_PIN_12

#define INSPECTION_SORT_OK_GPIO GPIOB
#define INSPECTION_SORT_OK_PIN GPIO_PIN_13

#define INSPECTION_SORT_NG_GPIO GPIOB
#define INSPECTION_SORT_NG_PIN GPIO_PIN_14

#define INSPECTION_SORT_RECHECK_GPIO GPIOB
#define INSPECTION_SORT_RECHECK_PIN GPIO_PIN_15

#define INSPECTION_POSITION_SENSOR_GPIO GPIOA
#define INSPECTION_POSITION_SENSOR_PIN GPIO_PIN_8
#define INSPECTION_POSITION_SENSOR_ACTIVE_LOW 1

#define INSPECTION_FAULT_INPUT_GPIO GPIOA
#define INSPECTION_FAULT_INPUT_PIN GPIO_PIN_11
#define INSPECTION_FAULT_INPUT_ACTIVE_LOW 1
