#!/usr/bin/env python3
from __future__ import annotations

"""Generate the frontend mock action catalog from the runtime action registry.

The generated catalog is a frontend fixture only; the source of truth remains
``upper_computer/config/system/action_registry.yaml`` plus the normalized
governance/capability readers in ``inspection_hmi_gateway.action_contract``.
"""

import argparse
import json
from pathlib import Path
import sys
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
for package_dir in sorted((ROOT / 'src').iterdir()):
    if package_dir.is_dir():
        sys.path.insert(0, str(package_dir))

from inspection_hmi_gateway.action_contract import PUBLIC_ACTION_API_SURFACE, action_catalog  # noqa: E402

TARGET = ROOT / 'frontend' / 'src' / 'mocks' / 'generated' / 'actionCatalog.ts'


def _literal(value: Any) -> str:
    return json.dumps(value, ensure_ascii=False)


def _list_literal(values: list[Any]) -> str:
    return '[' + ', '.join(_literal(value) for value in values) + ']'


def _entry_lines(entry: dict[str, Any]) -> list[str]:
    capability = entry.get('capability', {}) if isinstance(entry.get('capability', {}), dict) else {}
    governance = entry.get('governance', {}) if isinstance(entry.get('governance', {}), dict) else {}
    return [
        '  {',
        f'    kind: {_literal(entry.get("kind", ""))},',
        f'    type: {_literal(entry.get("type", ""))},',
        f'    topic: {_literal(entry.get("topic", ""))},',
        f'    requiredPayload: {_list_literal(list(entry.get("requiredPayload", [])))},',
        '    capability: {',
        f'      availability: {_literal(capability.get("availability", ""))},',
        f'      visibility: {_literal(capability.get("visibility", ""))},',
        f'      executionPolicy: {_literal(capability.get("executionPolicy", ""))},',
        f'      runtimeTruth: {_literal(capability.get("runtimeTruth", ""))},',
        f'      summary: {_literal(capability.get("summary", ""))},',
        f'      submitEnabled: {str(bool(capability.get("submitEnabled", False))).lower()},',
        f'      submitReason: {_literal(capability.get("submitReason", ""))},',
        '    },',
        '    governance: {',
        f'      tier: {_literal(governance.get("tier", ""))},',
        f'      lifecycle: {_literal(governance.get("lifecycle", ""))},',
        f'      sunsetRelease: {_literal(governance.get("sunsetRelease", ""))},',
        f'      promotionCriteria: {_list_literal(list(governance.get("promotionCriteria", [])))},',
        f'      requiredVerification: {_list_literal(list(governance.get("requiredVerification", [])))},',
        f'      documentationRefs: {_list_literal(list(governance.get("documentationRefs", [])))},',
        f'      uiLabel: {_literal(governance.get("uiLabel", ""))},',
        '    },',
        '  },',
    ]


def render() -> str:
    """Return the TypeScript fixture text derived from public production catalog.

    Returns:
        Generated TypeScript source.

    Boundary behavior:
        Internal, synthetic, experimental, and non-public actions are excluded by
        the same public catalog filter used by the gateway query plane. This keeps
        mock mode aligned with the operator-facing action surface.
    """
    entries = action_catalog(include_non_production=False, api_surface=PUBLIC_ACTION_API_SURFACE)
    lines = [
        '// Generated by upper_computer/scripts/generate_mock_action_catalog.py. Do not edit by hand.',
        "import type { ActionCatalogEntry } from '@/shared/types/domain';",
        '',
        'export const mockActionCatalog: ActionCatalogEntry[] = [',
    ]
    for entry in entries:
        lines.extend(_entry_lines(entry))
    lines.append('];')
    return '\n'.join(lines) + '\n'


def main() -> int:
    parser = argparse.ArgumentParser(description='Generate frontend mock action catalog from action registry.')
    parser.add_argument('--target', default=str(TARGET))
    parser.add_argument('--check', action='store_true', help='Fail if the generated file is out of date.')
    args = parser.parse_args()
    target = Path(args.target)
    rendered = render()
    if args.check:
        existing = target.read_text(encoding='utf-8') if target.exists() else ''
        if existing != rendered:
            print(f'mock action catalog is out of date: {target}', file=sys.stderr)
            return 1
        return 0
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(rendered, encoding='utf-8')
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
