#!/usr/bin/env bash
set -euo pipefail
ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"; ARTIFACT_DIR="$ROOT_DIR/.artifacts/verification"; LOG_DIR="$ARTIFACT_DIR/logs"; mkdir -p "$LOG_DIR"; COLCON_LOG="$LOG_DIR/ros_colcon.log"; TEST_RESULT_LOG="$LOG_DIR/ros_test_results.log"; PREFLIGHT_JSON="$ARTIFACT_DIR/ros_release_preflight.json"
cd "$ROOT_DIR"
if ! python3 "$ROOT_DIR/scripts/ros_release_gate_preflight.py" --workspace-root "$ROOT_DIR" --require-colcon --require-frontend-dist --write-json "$PREFLIGHT_JSON" > "$COLCON_LOG" 2>&1; then printf '%s\n' 'ROS release gate failed during preflight. See ros_release_preflight.json and ros_colcon.log for details.' >> "$COLCON_LOG"; printf '%s\n' 'ROS release gate failed before test execution; no colcon test results available.' > "$TEST_RESULT_LOG"; exit 1; fi
export INSPECTION_REQUIRE_FRONTEND_DIST=1
python3 "$ROOT_DIR/scripts/validate_action_registry_completeness.py" >> "$COLCON_LOG" 2>&1
export INSPECTION_REQUIRE_TYPED_INTERFACES=1
COLCON_BUILD_ARGS=(build --symlink-install --event-handlers console_direct+ --packages-up-to inspection_tests)
COLCON_TEST_ARGS=(test --event-handlers console_direct+ --packages-select inspection_tests --return-code-on-test-failure)
{ printf '[ros-release-gate] colcon %s
' "${COLCON_BUILD_ARGS[*]}"; colcon "${COLCON_BUILD_ARGS[@]}"; [ -f "$ROOT_DIR/install/setup.bash" ] || { printf '%s
' 'ROS release gate failed: install/setup.bash was not generated by colcon build.'; exit 1; }; source "$ROOT_DIR/install/setup.bash"; bash "$ROOT_DIR/scripts/run_ros_typed_interface_import_smoke.sh"; printf '[ros-release-gate] colcon %s
' "${COLCON_TEST_ARGS[*]}"; colcon "${COLCON_TEST_ARGS[@]}"; } > "$COLCON_LOG" 2>&1
{ source "$ROOT_DIR/install/setup.bash"; colcon test-result --verbose; } > "$TEST_RESULT_LOG" 2>&1
